### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by gabixdev**
Updated readme, probably there's different way, but people should use yarn

### CODE REVIEW

**Comment by DasWolke** [comment]
it does work though ?

**Comment by gabixdev** [comment]
Only via yarn

**Comment by MrLar** [comment]
Nope works via npm aswell

**Comment by gabixdev** [comment]
Does it run then?

**Comment by gabixdev** [comment]
For me wapi_core downloaded but it didn't run

**Comment by DasWolke** [comment]
Yep, it does work, you had a wrong dependency afaik.

**Pull request closed without merging**
